config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :seinens
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :seinen
end

app/models/seinen.rb
class Seinen < ApplicationRecord
  has_many :notes
  def to_s
    "#{title}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "La note a correctement été entrée." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "La note a correctement été mis à jour." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "La note a correctement été effacée." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:value, :seinen_id)
    end
end

app/controllers/seinens_controller.rb
class SeinensController < ApplicationController
  before_action :set_seinen, only: %i[ show edit update destroy ]

  # GET /seinens or /seinens.json
  def index
    @seinens = Seinen.all
  end

  # GET /seinens/1 or /seinens/1.json
  def show
  end

  # GET /seinens/new
  def new
    @seinen = Seinen.new
  end

  # GET /seinens/1/edit
  def edit
  end

  # POST /seinens or /seinens.json
  def create
    @seinen = Seinen.new(seinen_params)

    respond_to do |format|
      if @seinen.save
        format.html { redirect_to seinen_url(@seinen), notice: "Seinen was successfully created." }
        format.json { render :show, status: :created, location: @seinen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seinen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seinens/1 or /seinens/1.json
  def update
    respond_to do |format|
      if @seinen.update(seinen_params)
        format.html { redirect_to seinen_url(@seinen), notice: "Seinen was successfully updated." }
        format.json { render :show, status: :ok, location: @seinen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seinen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seinens/1 or /seinens/1.json
  def destroy
    @seinen.destroy


    respond_to do |format|
      format.html { redirect_to seinens_url, notice: "Seinen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seinen
      @seinen = Seinen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seinen_params
      params.require(:seinen).permit(:title, :article, :User_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/seinens_helper.rb
module SeinensHelper
end

app/views/home/index.html.erb
<div class="Logo">
  <h1>SeinenJump</h1>
</div>
<p id="notice"><%= notice %></p>




  <div class="buttonHome">
    <%= link_to "AVIS", "/seinens"%>
    <%= link_to "NOTES", "/notes"%>
  </div>

  <div class="LeSite">
  <div class="homeimg">
    <%= image_tag("tenma.png", {:style => "width:200px;"}) %>
    </div>
    <div class="LeSiteText">
      <h2>LE SITE</h2>
      <p>Seinen Jump est une Web App vous permettant de poster des avis et notes sur un ou plusieurs seinens. Comme vous, d’autres fans viendront poster des avis et notes et cela pourrait même vous donner envie de lire des œuvres encore inconnues de votre bibliothèque ! Pas de panique ! Aucune identification est requise, choisissez seulement un pseudonyme pour votre sécurité. </br> /!\ Avant de supprimer un avis, veuillez supprimer la note qui lui est donnée.</p>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeinenApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for note do |f| %>
  <%= f.input :value %>
  <%= f.association :seinen %>
  <%= f.button :submit, class: 'btn btn-primary' %>

<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Voir', @note %> |
<%= link_to 'Retour', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Note sur 10</th>
      <th>Seinen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.value %></td>
        <td><%= link_to note.seinen, note.seinen %></td>
        <td><%= link_to 'Voir', note %></td>
        <td><%= link_to 'Modifier', edit_note_path(note) %></td>
        <td><%= link_to 'Supprimer', note, method: :delete, data: { confirm: 'Êtes vous sûr(e)' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle note', new_note_path %>
<%= link_to "Accueil", root_path %>

app/views/notes/new.html.erb
<h1>Nouvelle note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note sur 10:</strong>
  <%= @note.value %>
</p>

<p>
  <strong>Seinen:</strong>
  <%= @note.seinen%>
</p>

<p>
  <strong>Seinen ID:</strong>
  <%= @note.seinen_id %>
</p>

<%= link_to 'Modifier', edit_note_path(@note) %> |
<%= link_to 'Retour', notes_path %>

app/views/seinens/_form.html.erb
<%= simple_form_for seinen do |f| %>
  <%= f.input :title %>
  <%= f.input :article  %>
  <%= f.input :User_name %>
  <%= f.button :submit, class: 'btn btn-primary' %>

<% end %>

app/views/seinens/edit.html.erb
<h1>Editing Seinen</h1>

<%= render 'form', seinen: @seinen %>

<%= link_to 'Show', @seinen %> |
<%= link_to 'Back', seinens_path %>

app/views/seinens/index.html.erb
<div class="Logo">
  <h1>SeinenJump</h1>
</div>
<p id="notice"><%= notice %></p>


<table class="table table-dark">
  <thead>
    <tr>
      <th>Title</th>
      <th>Article</th>
      <th>Nom d'utilisateur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seinens.each  do |seinen| %>
      <tr>
        <td><%= seinen.title %></td>
        <td><%= seinen.article.truncate(50) %></td>
        <td><%= seinen.User_name %></td>
        <td><%= link_to "Voir l'article en entier" , seinen %></td>
        <td><%= link_to 'Modifier', edit_seinen_path(seinen) %></td>
        <td><%= link_to 'Effacer', seinen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvel avis', new_seinen_path %>
<%= link_to "Accueil", root_path %>

app/views/seinens/new.html.erb
<div class="Logo">
    <h1>SeinenJump</h1>
  </div>
<h1>New Seinen</h1>

<%= render 'form', seinen: @seinen %>

<%= link_to 'Back', seinens_path %>

app/views/seinens/show.html.erb
<p id="notice"><%= notice %></p>

<p class="TitrePolice">
  <%= @seinen.title %>
</p>


<div class="article">
  <%= @seinen.notes.average(:value) %>
  <div class="description">
    <%= @seinen.article %>
  </div>
  </br>
  <div class="auteur">
    <%= @seinen.User_name.upcase %>
  </div>
  </br>
  <div class="ButtonShow">
    <%= link_to 'Modifier', edit_seinen_path(@seinen) %> |
    <%= link_to 'Retour', seinens_path %>
  </div>
</div>